# Generated by Django 5.1.6 on 2025-03-15 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_playlist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(choices=[('music', 'Music'), ('playlist', 'Playlist')], max_length=8)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.music')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.playlist')),
            ],
        ),
    ]
